# Generated by Django 4.1.6 on 2023-02-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[(1, 'на складе'), (2, 'в заказе')], help_text='Введите статус экземпляра книги', max_length=20, verbose_name='Cтaтyc экземпляра книги'),
        ),
    ]
