# Generated by Django 4.1.6 on 2023-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('На складе', 'На складе'), ('В заказе', 'В заказе')], help_text='Введите статус экземпляра книги', max_length=20, verbose_name='Cтaтyc экземпляра книги'),
        ),
    ]
